defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entyrPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoinst.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/cert.crt"
      keyFile = "/key.key"
